name: Pack Nuget File

on:
  push:
    branches: [ "main", "v*" ]
  pull_request:
    branches: [ "main", "v*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Install Android Workload
      run: dotnet workload install android
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Pack
      run: dotnet pack -c Release --no-build
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Package
        path: ./MattiasCibien.Extensions.Logging.Logcat/bin/Release/*.*nupkg
    - name: Publish to NuGet
      if: github.event_name != 'pull_request'
      run: dotnet nuget push ./MattiasCibien.Extensions.Logging.Logcat/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key ${{ secrets.NUGET_KEY }}
    - name: Publish Symbols to NuGet
      if: github.event_name != 'pull_request'
      run: dotnet nuget push ./MattiasCibien.Extensions.Logging.Logcat/bin/Release/*.snupkg --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key ${{ secrets.NUGET_KEY }}
